apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-front-mcp
  namespace: pets
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: store-front-mcp.__INGRESS_IP__.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-front-mcp
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-admin-mcp
  namespace: pets
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: store-admin-mcp.__INGRESS_IP__.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-admin-mcp
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-front
  namespace: pets
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: store-front.__INGRESS_IP__.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-front
                port:
                  number: 80
